name: Bug 提交
description: 提交产品缺陷帮助我更好的改进
title: "[Bug]"
labels: 'Bug'
assignees: ChishFoxcat
body:
  - type: markdown
    id: enviroment
    attributes:
      value: "## 提供信息"
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: "应用版本"
      description: "进入设置关于页面查看"
  - type: input
    id: device
    validations:
      required: true
    attributes:
      label: "设备信息"
      description: "手机型号、系统版本"
  - type: input
    id: contacts
    attributes:
      label: "联系方式"
      description: "可以联系到你的方式：QQ、微信、邮箱等"
  - type: markdown
    id: details
    attributes:
      value: "## 详细描述"
  - type: textarea
    id: happened
    validations:
      required: true
    attributes:
      label: "发生了什么？"
      description: "描述你遇到的问题，并描述怎么触发的"
  - type: textarea
    id: expect
    attributes:
      label: "你期待正确的是什么？"
  - type: textarea
    id: screenshot
    attributes:
      label: "截图"
      description: "如果可以的话，提供截图或者视频"
    
